from .animals import Animal
from .anglerfish import AnglerFish
from .betafish import Betafish
from .camel import Camel
from .cat import Cat
from .clownfish import Clownfish
from .elephant import Elephant
from .giraffe import Giraffe
from .goldfish import Goldfish
from .horse import Horse
from .monkey import Monkey
from .shark import Shark
from .snake import Snake